version: "3.9"

services:
  backend:
    # 后端镜像构建目录
    build: ./backend
    # 后端默认端口映射
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
    restart: always   # 自动重启容器，生产建议加
    env_file:
      - .env.production
    volumes:
      - nova_data:/app/storage  # 挂载到容器内 /app/storage

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile.celery
    depends_on:
      - redis
    restart: always   # 自动重启容器，生产建议加
    env_file:
      - .env.production
    volumes:
      - nova_data:/app/storage  # 挂载到容器内 /app/storage
      - ./backend/storage/effects:/app/storage/effects
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           device_ids: [ '0' ]
    #           capabilities: [ compute, utility ]

  redis:
    # 轻量级 Redis 镜像
    image: redis:7.0-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    restart: always   # 自动重启容器，生产建议加
    env_file:
      - .env.production

  frontend:
    build: ./frontend
    ports:
      - "7860:80"  # 生产环境用 nginx，对外端口改为 7860
    restart: always   # 自动重启容器，生产建议加
    env_file:
      - .env.production

volumes:
  nova_data:
