FROM python:3.11-slim-bullseye

WORKDIR /app

RUN apt-get update && \
	apt-get install -y --no-install-recommends ffmpeg && \
	rm -rf /var/lib/apt/lists/* 

COPY requirements.txt .
RUN --mount=type=cache,target=/root/.cache/pip pip install -r requirements.txt

COPY . .

CMD ["celery", "-A", "app.celery_app", "worker", "--loglevel=info"]
# CMD ["python", "worker/worker.py"]
